# dev stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
COPY vue.config.js ./
COPY babel.config.js ./
RUN npm install
COPY . .
RUN npm run build

# Set environment variables
ENV NODE_ENV=development

# Build the Vue.js application
RUN npm run build

# Start the application
CMD [ "npm", "run", "serve" ]